source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "csv" # Explicitly added to resolve Ruby 3.4.0+ default-gem compatibility
gem "base64" # Explicitly added to resolve Ruby 3.4.0+ default-gem compatibility
gem "webrick" # Explicitly added to resolve Ruby 3.0.0+ default-gem compatibility

# Specify the plugins and themes used by your GitHub Pages site
group :jekyll_plugins do
  gem "just-the-docs"
  gem "jekyll-seo-tag"
  gem "jekyll-default-layout"
  gem "jekyll-remote-theme"
  gem "jekyll-relative-links"
end
