config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  ComplexCondition:
    active: true
    allowedConditions: 4
  ComplexInterface:
    active: true
    allowedDefinitions: 50
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 30
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
  LargeClass:
    active: true
    allowedLines: 600
  LongMethod:
    active: true
    allowedLines: 300
  LongParameterList:
    active: true
    allowedFunctionParameters: 10
    allowedConstructorParameters: 10
    ignoreDefaultParameters: false
    ignoreDataClasses: true
  NestedBlockDepth:
    active: true
    allowedDepth: 4
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 100
    allowedFunctionsPerClass: 100
    allowedFunctionsPerInterface: 100
    allowedFunctionsPerObject: 100
    allowedFunctionsPerEnum: 11

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
  InstanceOfCheckForException:
    active: true
  SwallowedException:
    active: true
  TooGenericExceptionCaught:
    active: true
  TooGenericExceptionThrown:
    active: true

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][a-zA-Z0-9]*'
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][A-Z_0-9]*|[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '([a-z][a-zA-Z0-9]*)|(`[a-zA-Z0-9 ]+`)' # Support backtick names in tests
  ObjectPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][a-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Z_0-9]*|[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'

performance:
  active: true
  ArrayPrimitive:
    active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
  Deprecation:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnsafeCast:
    active: true

style:
  active: true
  UnnecessaryFullyQualifiedName:
    active: true
  CollapsibleIfStatements:
    active: false
  ForbiddenComment:
    active: true
    comments:
      - value: 'TODO:'
      - value: 'FIXME:'
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreEnums: true
    ignoreRanges: true
  MaxLineLength:
    active: false
    maxLineLength: 120
  MayBeConstant:
    active: true
  ModifierOrder:
    active: true
  NestedClassesVisibility:
    active: true
  ReturnCount:
    active: true
    max: 8
  SafeCast:
    active: true
  UnusedImport:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateFunction:
    active: true
  UnusedPrivateProperty:
    active: true
  UseDataClass:
    active: false
  WildcardImport:
    active: true
    excludeImports: ['org.junit.jupiter.api.Assertions.*']
  ThrowsCount:
    active: false



