/*
 * Copyright 2026 The Konture Contributors
 * Contributors: Bao Le Duc (@baole)
 * SPDX-License-Identifier: Apache-2.0
 */

package io.github.baole.konture.core.model

import kotlinx.serialization.Serializable

/**
 * Aggregated report containing rule violations for a given rule execution.
 *
 * @property ruleId The identifier of the verified rule.
 * @property violations List of violations generated by the rule execution.
 * @property severity Overall report severity level.
 */
@Serializable
public data class ViolationReport(
    val ruleId: String,
    val violations: List<Violation>,
    val severity: Severity = Severity.ERROR,
) {
    public val hasErrors: Boolean get() = violations.any { it.severity == Severity.ERROR }
    public val hasWarnings: Boolean get() = violations.any { it.severity == Severity.WARNING }
}
